Exception error message
/opt/project/tests/Fixtures/ExceptionInside.php:9
#0 /opt/project/vendor/hyqo/container/src/Container.php(75): Hyqo\Task\Test\Fixtures\ExceptionInside->__invoke()
#1 /opt/project/src/Task.php(95): Hyqo\Container\Container->call(Array, Array)
#2 /opt/project/src/Handler.php(37): Hyqo\Task\Task->run(Array)
#3 /opt/project/tests/HandlerTest.php(52): Hyqo\Task\Handler->handle(Array)
#4 /opt/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(1527): Hyqo\Task\Test\HandlerTest->test_exception_inside()
#5 /opt/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(1133): PHPUnit\Framework\TestCase->runTest()
#6 /opt/project/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#7 /opt/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(885): PHPUnit\Framework\TestResult->run(Object(Hyqo\Task\Test\HandlerTest))
#8 /opt/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 /opt/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /opt/project/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(670): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 /opt/project/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#12 /opt/project/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#13 /opt/project/vendor/phpunit/phpunit/phpunit(92): PHPUnit\TextUI\Command::main()
#14 {main}
